sbatch ./foursquare_scheme1_submit_01.sh
sbatch ./foursquare_scheme1_submit_02.sh
sbatch ./foursquare_scheme1_submit_03.sh
sbatch ./foursquare_scheme1_submit_04.sh
sbatch ./foursquare_scheme1_submit_05.sh
sbatch ./foursquare_scheme1_submit_06.sh
sbatch ./foursquare_scheme1_submit_07.sh
sbatch ./foursquare_scheme1_submit_08.sh
sbatch ./foursquare_scheme1_submit_09.sh
sbatch ./foursquare_scheme2_submit_10.sh
sbatch ./foursquare_scheme2_submit_11.sh
sbatch ./foursquare_scheme2_submit_12.sh
sbatch ./foursquare_scheme2_submit_13.sh
sbatch ./foursquare_scheme2_submit_14.sh
sbatch ./foursquare_scheme2_submit_15.sh
sbatch ./foursquare_scheme2_submit_16.sh
sbatch ./foursquare_scheme2_submit_17.sh
sbatch ./foursquare_scheme2_submit_18.sh
sbatch ./gowalla_scheme1_submit_01.sh
sbatch ./gowalla_scheme1_submit_02.sh
sbatch ./gowalla_scheme1_submit_03.sh
sbatch ./gowalla_scheme1_submit_04.sh
sbatch ./gowalla_scheme1_submit_05.sh
sbatch ./gowalla_scheme1_submit_06.sh
sbatch ./gowalla_scheme1_submit_07.sh
sbatch ./gowalla_scheme1_submit_08.sh
sbatch ./gowalla_scheme1_submit_09.sh
sbatch ./gowalla_scheme2_submit_10.sh
sbatch ./gowalla_scheme2_submit_11.sh
sbatch ./gowalla_scheme2_submit_12.sh
sbatch ./gowalla_scheme2_submit_13.sh
sbatch ./gowalla_scheme2_submit_14.sh
sbatch ./gowalla_scheme2_submit_15.sh
sbatch ./gowalla_scheme2_submit_16.sh
sbatch ./gowalla_scheme2_submit_17.sh
sbatch ./gowalla_scheme2_submit_18.sh